### ISSUE TITLE
ImportError: failed to find libmagic

### ISSUE THREAD

**Issue by sewonist** [hynchl/distribusi-foh#7]
**Environments**

* Anaconda - Python 3.6
* macOS 10.15.7

```
Traceback (most recent call last):
  File "distribusi/test.py", line 3, in <module>
    from distribusi.cli import build_argparser, distribusify
  File "/Users/sewonist/Projects/99.fragments/05.Projects/distribusi-foh/distribusi/distribusi/cli.py", line 5, in <module>
    from distribusi.distribusi import distribusify
  File "/Users/sewonist/Projects/99.fragments/05.Projects/distribusi-foh/distribusi/distribusi/distribusi.py", line 9, in <module>
    import magic
  File "/Users/sewonist/opt/anaconda3/envs/distribusi-foh/lib/python3.6/site-packages/magic.py", line 201, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

**Comment by sewonist** [comment]
macOS 에서 libmagic 을 설치하면 됨.

```
brew install libmagic
```
